package com.miningmark48.bam.init;

import com.miningmark48.bam.creativetab.CreativeTabBAM;
import com.miningmark48.bam.item.*;
import com.miningmark48.bam.reference.Reference;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;

public class ModItems {

    //Fish
    public static final Item aaFish = new ItemFish().setUnlocalizedName("aaFish").setTextureName(Reference.MOD_ID + ":aaFish");
    public static final Item aaFish2 = new ItemFish().setUnlocalizedName("aaFish2").setTextureName(Reference.MOD_ID + ":aaFish2");
    public static final Item aaFish3 = new ItemFish().setUnlocalizedName("aaFish3").setTextureName(Reference.MOD_ID + ":aaFish3");
    public static final Item abFish = new ItemFish().setUnlocalizedName("abFish").setTextureName(Reference.MOD_ID + ":abFish");
    public static final Item acFish = new ItemFish().setUnlocalizedName("acFish").setTextureName(Reference.MOD_ID + ":acFish");
    public static final Item acFish2 = new ItemFish().setUnlocalizedName("acFish2").setTextureName(Reference.MOD_ID + ":acFish2");
    public static final Item afFish = new ItemFish().setUnlocalizedName("afFish").setTextureName(Reference.MOD_ID + ":afFish");
    public static final Item ahFish = new ItemFish().setUnlocalizedName("ahFish").setTextureName(Reference.MOD_ID + ":ahFish");
    public static final Item ajFish = new ItemFish().setUnlocalizedName("ajFish").setTextureName(Reference.MOD_ID + ":ajFish");
    public static final Item ajFish2 = new ItemFish().setUnlocalizedName("ajFish2").setTextureName(Reference.MOD_ID + ":ajFish2");
    public static final Item alFish = new ItemFish().setUnlocalizedName("alFish").setTextureName(Reference.MOD_ID + ":alFish");
    public static final Item aoFish = new ItemFish().setUnlocalizedName("aoFish").setTextureName(Reference.MOD_ID + ":aoFish");
    public static final Item anFish = new ItemFish().setUnlocalizedName("anFish").setTextureName(Reference.MOD_ID + ":anFish");
    public static final Item arFish = new ItemFish().setUnlocalizedName("arFish").setTextureName(Reference.MOD_ID + ":arFish");
    public static final Item arFish2 = new ItemFish().setUnlocalizedName("arFish2").setTextureName(Reference.MOD_ID + ":arFish2");
    public static final Item arFish3 = new ItemFish().setUnlocalizedName("arFish3").setTextureName(Reference.MOD_ID + ":arFish3");
    public static final Item asFish = new ItemFish().setUnlocalizedName("asFish").setTextureName(Reference.MOD_ID + ":asFish");
    public static final Item asFish2 = new ItemFish().setUnlocalizedName("asFish2").setTextureName(Reference.MOD_ID + ":asFish2");
    public static final Item asFish3 = new ItemFish().setUnlocalizedName("asFish3").setTextureName(Reference.MOD_ID + ":asFish3");
    public static final Item aspFish = new ItemFish().setUnlocalizedName("aspFish").setTextureName(Reference.MOD_ID + ":aspFish");
    public static final Item aspFish2 = new ItemFish().setUnlocalizedName("aspFish2").setTextureName(Reference.MOD_ID + ":aspFish2");
    public static final Item aspFish3 = new ItemFish().setUnlocalizedName("aspFish3").setTextureName(Reference.MOD_ID + ":aspFish3");
    public static final Item aspFish4 = new ItemFish().setUnlocalizedName("aspFish4").setTextureName(Reference.MOD_ID + ":aspFish4");
    public static final Item aspFish5 = new ItemFish().setUnlocalizedName("aspFish5").setTextureName(Reference.MOD_ID + ":aspFish5");
    public static final Item aspFish6 = new ItemFish().setUnlocalizedName("aspFish6").setTextureName(Reference.MOD_ID + ":aspFish6");
    public static final Item atFish = new ItemFish().setUnlocalizedName("atFish").setTextureName(Reference.MOD_ID + ":atFish");
    public static final Item bcFish = new ItemFish().setUnlocalizedName("bcFish").setTextureName(Reference.MOD_ID + ":bcFish");
    public static final Item bfFish = new ItemFish().setUnlocalizedName("bfFish").setTextureName(Reference.MOD_ID + ":bfFish");
    public static final Item blFish = new ItemFish().setUnlocalizedName("blFish").setTextureName(Reference.MOD_ID + ":blFish");
    public static final Item cfFish = new ItemFish().setUnlocalizedName("cfFish").setTextureName(Reference.MOD_ID + ":cfFish");
    public static final Item bmFish = new ItemFish().setUnlocalizedName("bmFish").setTextureName(Reference.MOD_ID + ":bmFish");
    public static final Item gtFish = new ItemFish().setUnlocalizedName("gtFish").setTextureName(Reference.MOD_ID + ":gtFish");
    public static final Item hcFish = new ItemFish().setUnlocalizedName("hcFish").setTextureName(Reference.MOD_ID + ":hcFish");
    public static final Item heFish = new ItemFish().setUnlocalizedName("heFish").setTextureName(Reference.MOD_ID + ":heFish");
    public static final Item hhFish = new ItemFish().setUnlocalizedName("hhFish").setTextureName(Reference.MOD_ID + ":hhFish");
    public static final Item hhFish2 = new ItemFish().setUnlocalizedName("hhFish2").setTextureName(Reference.MOD_ID + ":hhFish2");
    public static final Item hpFish = new ItemFish().setUnlocalizedName("hpFish").setTextureName(Reference.MOD_ID + ":hpFish");
    public static final Item hrFish = new ItemFish().setUnlocalizedName("hrFish").setTextureName(Reference.MOD_ID + ":hrFish");
    public static final Item isFish = new ItemFish().setUnlocalizedName("isFish").setTextureName(Reference.MOD_ID + ":isFish");
    public static final Item hsFish = new ItemFish().setUnlocalizedName("hsFish").setTextureName(Reference.MOD_ID + ":hsFish");
    public static final Item hspFish = new ItemFish().setUnlocalizedName("hspFish").setTextureName(Reference.MOD_ID + ":hspFish");
    public static final Item hzFish = new ItemFish().setUnlocalizedName("hzFish").setTextureName(Reference.MOD_ID + ":hzFish");
    public static final Item lcFish = new ItemFish().setUnlocalizedName("lcFish").setTextureName(Reference.MOD_ID + ":lcFish");
    public static final Item ltFish = new ItemFish().setUnlocalizedName("ltFish").setTextureName(Reference.MOD_ID + ":ltFish");
    public static final Item mcFish = new ItemFish().setUnlocalizedName("mcFish").setTextureName(Reference.MOD_ID + ":mcFish");
    public static final Item mcFish2 = new ItemFish().setUnlocalizedName("mcFish2").setTextureName(Reference.MOD_ID + ":mcFish2");
    public static final Item mdFish = new ItemFish().setUnlocalizedName("mdFish").setTextureName(Reference.MOD_ID + ":mdFish");
    public static final Item meFish = new ItemFish().setUnlocalizedName("meFish").setTextureName(Reference.MOD_ID + ":meFish");
    public static final Item mlFish = new ItemFish().setUnlocalizedName("mlFish").setTextureName(Reference.MOD_ID + ":mlFish");
    public static final Item nsFish = new ItemFish().setUnlocalizedName("nsFish").setTextureName(Reference.MOD_ID + ":nsFish");
    public static final Item pwFish = new ItemFish().setUnlocalizedName("pwFish").setTextureName(Reference.MOD_ID + ":pwFish");
    public static final Item sfFish = new ItemFish().setUnlocalizedName("sfFish").setTextureName(Reference.MOD_ID + ":sfFish");
    public static final Item paFish = new ItemFish().setUnlocalizedName("paFish").setTextureName(Reference.MOD_ID + ":paFish");
    public static final Item paFish2 = new ItemFish().setUnlocalizedName("paFish2").setTextureName(Reference.MOD_ID + ":paFish2");
    public static final Item pdFish = new ItemFish().setUnlocalizedName("pdFish").setTextureName(Reference.MOD_ID + ":pdFish");
    public static final Item psFish = new ItemFish().setUnlocalizedName("psFish").setTextureName(Reference.MOD_ID + ":psFish");
    public static final Item paFish3 = new ItemFish().setUnlocalizedName("paFish3").setTextureName(Reference.MOD_ID + ":paFish3");
    public static final Item pnFish3 = new ItemFish().setUnlocalizedName("pnFish3").setTextureName(Reference.MOD_ID + ":pnFish3");
    public static final Item ptFish = new ItemFish().setUnlocalizedName("ptFish").setTextureName(Reference.MOD_ID + ":ptFish");
    public static final Item smFish = new ItemFish().setUnlocalizedName("smFish").setTextureName(Reference.MOD_ID + ":smFish");
    public static final Item vmFish = new ItemFish().setUnlocalizedName("vmFish").setTextureName(Reference.MOD_ID + ":vmFish");
    public static final Item xhFish = new ItemFish().setUnlocalizedName("xhFish").setTextureName(Reference.MOD_ID + ":xhFish");
    public static final Item xhFish2 = new ItemFish().setUnlocalizedName("xhFish2").setTextureName(Reference.MOD_ID + ":xhFish2");
    public static final Item nlFish = new ItemFish().setUnlocalizedName("nlFish").setTextureName(Reference.MOD_ID + ":nlFish");
    public static final Item ogFish = new ItemFish().setUnlocalizedName("ogFish").setTextureName(Reference.MOD_ID + ":ogFish");
    public static final Item okFish = new ItemFish().setUnlocalizedName("okFish").setTextureName(Reference.MOD_ID + ":okFish");
    public static final Item okFish2 = new ItemFish().setUnlocalizedName("okFish2").setTextureName(Reference.MOD_ID + ":okFish2");
    public static final Item omFish = new ItemFish().setUnlocalizedName("omFish").setTextureName(Reference.MOD_ID + ":omFish");
    public static final Item omFish2 = new ItemFish().setUnlocalizedName("omFish2").setTextureName(Reference.MOD_ID + ":omFish2");
    public static final Item otFish = new ItemFish().setUnlocalizedName("otFish").setTextureName(Reference.MOD_ID + ":otFish");
    public static final Item pnFish = new ItemFish().setUnlocalizedName("pnFish").setTextureName(Reference.MOD_ID + ":pnFish");
    public static final Item pnFish2 = new ItemFish().setUnlocalizedName("pnFish2").setTextureName(Reference.MOD_ID + ":pnFish2");
    public static final Item psmFish = new ItemFish().setUnlocalizedName("psmFish").setTextureName(Reference.MOD_ID + ":psmFish");
    public static final Item pcFish = new ItemFish().setUnlocalizedName("pcFish").setTextureName(Reference.MOD_ID + ":pcFish");
    public static final Item psFish2 = new ItemFish().setUnlocalizedName("psFish2").setTextureName(Reference.MOD_ID + ":psFish2");
    public static final Item phFish = new ItemFish().setUnlocalizedName("phFish").setTextureName(Reference.MOD_ID + ":phFish");
    public static final Item pmFish = new ItemFish().setUnlocalizedName("pmFish").setTextureName(Reference.MOD_ID + ":pmFish");
    public static final Item pmvFish = new ItemFish().setUnlocalizedName("pmvFish").setTextureName(Reference.MOD_ID + ":pmvFish");
    public static final Item poFish = new ItemFish().setUnlocalizedName("poFish").setTextureName(Reference.MOD_ID + ":poFish");
    public static final Item poFish2 = new ItemFish().setUnlocalizedName("poFish2").setTextureName(Reference.MOD_ID + ":poFish2");
    public static final Item asFish4 = new ItemFish().setUnlocalizedName("asFish4").setTextureName(Reference.MOD_ID + ":asFish4");
    public static final Item acFish3 = new ItemFish().setUnlocalizedName("acFish3").setTextureName(Reference.MOD_ID + ":acFish3");
    public static final Item ccFish = new ItemFish().setUnlocalizedName("ccFish").setTextureName(Reference.MOD_ID + ":ccFish");
    public static final Item eaFish = new ItemFish().setUnlocalizedName("eaFish").setTextureName(Reference.MOD_ID + ":eaFish");
    public static final Item elFish = new ItemFish().setUnlocalizedName("elFish").setTextureName(Reference.MOD_ID + ":elFish");
    public static final Item emFish = new ItemFish().setUnlocalizedName("emFish").setTextureName(Reference.MOD_ID + ":emFish");
    public static final Item ipFish = new ItemFish().setUnlocalizedName("ipFish").setTextureName(Reference.MOD_ID + ":ipFish");
    public static final Item lgFish = new ItemFish().setUnlocalizedName("lgFish").setTextureName(Reference.MOD_ID + ":lgFish");
    public static final Item mdFish2 = new ItemFish().setUnlocalizedName("mdFish2").setTextureName(Reference.MOD_ID + ":mdFish2");
    public static final Item maFish = new ItemFish().setUnlocalizedName("maFish").setTextureName(Reference.MOD_ID + ":maFish");
    public static final Item msFish = new ItemFish().setUnlocalizedName("msFish").setTextureName(Reference.MOD_ID + ":msFish");
    public static final Item paFish4 = new ItemFish().setUnlocalizedName("paFish4").setTextureName(Reference.MOD_ID + ":paFish4");
    public static final Item stFish = new ItemFish().setUnlocalizedName("stFish").setTextureName(Reference.MOD_ID + ":stFish");
    public static final Item scFish = new ItemFish().setUnlocalizedName("scFish").setTextureName(Reference.MOD_ID + ":scFish");
    public static final Item aFish = new ItemFish().setUnlocalizedName("aFish").setTextureName(Reference.MOD_ID + ":aFish");
    public static final Item arFish4 = new ItemFish().setUnlocalizedName("arFish4").setTextureName(Reference.MOD_ID + ":arFish4");
    public static final Item caFish = new ItemFish().setUnlocalizedName("caFish").setTextureName(Reference.MOD_ID + ":caFish");
    public static final Item emFish2 = new ItemFish().setUnlocalizedName("emFish2").setTextureName(Reference.MOD_ID + ":emFish2");
    public static final Item enFish = new ItemFish().setUnlocalizedName("enFish").setTextureName(Reference.MOD_ID + ":enFish");
    public static final Item laFish = new ItemFish().setUnlocalizedName("laFish").setTextureName(Reference.MOD_ID + ":laFish");
    public static final Item lmFish = new ItemFish().setUnlocalizedName("lmFish").setTextureName(Reference.MOD_ID + ":lmFish");
    public static final Item msFish2 = new ItemFish().setUnlocalizedName("msFish2").setTextureName(Reference.MOD_ID + ":msFish2");
    public static final Item mcFish3 = new ItemFish().setUnlocalizedName("mcFish3").setTextureName(Reference.MOD_ID + ":mcFish3");
    public static final Item pfFish = new ItemFish().setUnlocalizedName("pfFish").setTextureName(Reference.MOD_ID + ":pfFish");
    public static final Item pnFish4 = new ItemFish().setUnlocalizedName("pnFish4").setTextureName(Reference.MOD_ID + ":pnFish4");
    public static final Item poFish3 = new ItemFish().setUnlocalizedName("poFish3").setTextureName(Reference.MOD_ID + ":poFish3");
    public static final Item sfFish2 = new ItemFish().setUnlocalizedName("sfFish2").setTextureName(Reference.MOD_ID + ":sfFish2");
    public static final Item svFish = new ItemFish().setUnlocalizedName("svFish").setTextureName(Reference.MOD_ID + ":svFish");
    public static final Item cbFish = new ItemFish().setUnlocalizedName("cbFish").setTextureName(Reference.MOD_ID + ":cbFish");
    public static final Item clFish = new ItemFish().setUnlocalizedName("clFish").setTextureName(Reference.MOD_ID + ":clFish");
    public static final Item clFish2 = new ItemFish().setUnlocalizedName("clFish2").setTextureName(Reference.MOD_ID + ":clFish2");
    public static final Item ccFish2 = new ItemFish().setUnlocalizedName("ccFish2").setTextureName(Reference.MOD_ID + ":ccFish2");
    public static final Item gcFish = new ItemFish().setUnlocalizedName("gcFish").setTextureName(Reference.MOD_ID + ":gcFish");
    public static final Item ioFish = new ItemFish().setUnlocalizedName("ioFish").setTextureName(Reference.MOD_ID + ":ioFish");
    public static final Item ioFish2 = new ItemFish().setUnlocalizedName("ioFish2").setTextureName(Reference.MOD_ID + ":ioFish2");
    public static final Item nbFish = new ItemFish().setUnlocalizedName("nbFish").setTextureName(Reference.MOD_ID + ":nbFish");
    public static final Item sFish = new ItemFish().setUnlocalizedName("sFish").setTextureName(Reference.MOD_ID + ":sFish");

    //Fishing Rods
    public static final Item whiteRod = new ItemWhiteRod().setUnlocalizedName("whiteRod").setTextureName(Reference.MOD_ID + ":whiteRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);
    public static final Item greyRod = new ItemGreyRod().setUnlocalizedName("greyRod").setTextureName(Reference.MOD_ID + ":greyRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);
    public static final Item lightBlueRod = new ItemLightBlueRod().setUnlocalizedName("lightBlueRod").setTextureName(Reference.MOD_ID + ":lightBlueRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);
    //Rods and Reels
    public static final Item whiteToolRod = new ItemRod().setUnlocalizedName("whiteToolRod").setTextureName(Reference.MOD_ID + ":whiteToolRod").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item greyToolRod = new ItemRod().setUnlocalizedName("greyToolRod").setTextureName(Reference.MOD_ID + ":greyToolRod").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item lightBlueToolRod = new ItemRod().setUnlocalizedName("lightBlueToolRod").setTextureName(Reference.MOD_ID + ":lightBlueToolRod").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item whiteReel = new ItemRod().setUnlocalizedName("whiteReel").setTextureName(Reference.MOD_ID + ":whiteReel").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item greyReel = new ItemRod().setUnlocalizedName("greyReel").setTextureName(Reference.MOD_ID + ":greyReel").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item lightBlueReel = new ItemRod().setUnlocalizedName("lightBlueReel").setTextureName(Reference.MOD_ID + ":lightBlueReel").setCreativeTab(CreativeTabBAM.BAM_Tab);

    //Ingots/Nuggets
    public static final Item copperIngot = new ItemIngot().setUnlocalizedName("copperIngot").setTextureName(Reference.MOD_ID + ":copperIngot").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item tinIngot = new ItemIngot().setUnlocalizedName("tinIngot").setTextureName(Reference.MOD_ID + ":tinIngot").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item silverIngot = new ItemIngot().setUnlocalizedName("silverIngot").setTextureName(Reference.MOD_ID + ":silverIngot").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item tungstenIngot = new ItemIngot().setUnlocalizedName("tungstenIngot").setTextureName(Reference.MOD_ID + ":tungstenIngot").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arsenicIngot = new ItemIngot().setUnlocalizedName("arsenicIngot").setTextureName(Reference.MOD_ID + ":arsenicIngot").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item copperNugget = new ItemNugget().setUnlocalizedName("copperNugget").setTextureName(Reference.MOD_ID + ":copperNugget").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item tinNugget = new ItemNugget().setUnlocalizedName("tinNugget").setTextureName(Reference.MOD_ID + ":tinNugget").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item silverNugget = new ItemNugget().setUnlocalizedName("silverNugget").setTextureName(Reference.MOD_ID + ":silverNugget").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item tungstenNugget = new ItemNugget().setUnlocalizedName("tungstenNugget").setTextureName(Reference.MOD_ID + ":tungstenNugget").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arsenicNugget = new ItemNugget().setUnlocalizedName("arsenicNugget").setTextureName(Reference.MOD_ID + ":arsenicNugget").setCreativeTab(CreativeTabBAM.BAM_Tab);

    //Fish
    public static final Item cavierBowl = new ItemBAMFood(4, 1.0F, true).setUnlocalizedName("cavierBowl").setTextureName(Reference.MOD_ID + ":cavierBowl").setCreativeTab(CreativeTabBAM.BAM_Tab);

    //Misc
    public static final Item fishingLine = new ItemBAM().setUnlocalizedName("fishingLine").setTextureName(Reference.MOD_ID + ":fishingLine").setCreativeTab(CreativeTabBAM.BAM_Tab);


    public static void init() {

        GameRegistry.registerItem(aaFish, "aaFish");
        GameRegistry.registerItem(aaFish2, "aaFish2");
        GameRegistry.registerItem(aaFish3, "aaFish3");
        GameRegistry.registerItem(abFish, "abFish");
        GameRegistry.registerItem(acFish, "acFish");
        GameRegistry.registerItem(acFish2, "acFish2");
        GameRegistry.registerItem(afFish, "afFish");
        GameRegistry.registerItem(ahFish, "ahFish");
        GameRegistry.registerItem(ajFish, "ajFish");
        GameRegistry.registerItem(ajFish2, "ajFish2");
        GameRegistry.registerItem(alFish, "alFish");
        GameRegistry.registerItem(aoFish, "aoFish");
        GameRegistry.registerItem(anFish, "anFish");
        GameRegistry.registerItem(arFish, "arFish");
        GameRegistry.registerItem(arFish2, "arFish2");
        GameRegistry.registerItem(arFish3, "arFish3");
        GameRegistry.registerItem(asFish, "asFish");
        GameRegistry.registerItem(asFish2, "asFish2");
        GameRegistry.registerItem(asFish3, "asFish3");
        GameRegistry.registerItem(aspFish, "aspFish");
        GameRegistry.registerItem(aspFish2, "aspFish2");
        GameRegistry.registerItem(aspFish3, "aspFish3");
        GameRegistry.registerItem(aspFish4, "aspFish4");
        GameRegistry.registerItem(aspFish5, "aspFish5");
        GameRegistry.registerItem(aspFish6, "aspFish6");
        GameRegistry.registerItem(atFish, "atFish");
        GameRegistry.registerItem(bcFish, "bcFish");
        GameRegistry.registerItem(bfFish, "bfFish");
        GameRegistry.registerItem(blFish, "blFish");
        GameRegistry.registerItem(bmFish, "bmFish");
        GameRegistry.registerItem(cfFish, "cfFish");
        GameRegistry.registerItem(gtFish, "gtFish");
        GameRegistry.registerItem(hcFish, "hcFish");
        GameRegistry.registerItem(heFish, "heFish");
        GameRegistry.registerItem(hhFish, "hhFish");
        GameRegistry.registerItem(hhFish2, "hhFish2");
        GameRegistry.registerItem(hpFish, "hpFish");
        GameRegistry.registerItem(hrFish, "hrFish");
        GameRegistry.registerItem(hsFish, "hsFish");
        GameRegistry.registerItem(hspFish, "hspFish");
        GameRegistry.registerItem(hzFish, "hzFish");
        GameRegistry.registerItem(isFish, "isFish");
        GameRegistry.registerItem(lcFish, "lcFish");
        GameRegistry.registerItem(ltFish, "ltFish");
        GameRegistry.registerItem(mcFish, "mcFish");
        GameRegistry.registerItem(mcFish2, "mcFish2");
        GameRegistry.registerItem(mdFish, "mdFish");
        GameRegistry.registerItem(meFish, "meFish");
        GameRegistry.registerItem(mlFish, "mlFish");
        GameRegistry.registerItem(nsFish, "nsFish");
        GameRegistry.registerItem(pwFish, "pwFish");
        GameRegistry.registerItem(sfFish, "sfFish");
        GameRegistry.registerItem(paFish, "paFish");
        GameRegistry.registerItem(paFish2, "paFish2");
        GameRegistry.registerItem(pdFish, "pdFish");
        GameRegistry.registerItem(psFish, "psFish");
        GameRegistry.registerItem(paFish3, "paFish3");
        GameRegistry.registerItem(pnFish3, "pnFish3");
        GameRegistry.registerItem(ptFish, "ptFish");
        GameRegistry.registerItem(smFish, "smFish");
        GameRegistry.registerItem(vmFish, "vmFish");
        GameRegistry.registerItem(xhFish, "xhFish");
        GameRegistry.registerItem(xhFish2, "xhFish2");
        GameRegistry.registerItem(nlFish, "nlFish");
        GameRegistry.registerItem(ogFish, "ogFish");
        GameRegistry.registerItem(okFish, "okFish");
        GameRegistry.registerItem(okFish2, "okFish2");
        GameRegistry.registerItem(omFish, "omFish");
        GameRegistry.registerItem(omFish2, "omFish2");
        GameRegistry.registerItem(otFish, "otFish");
        GameRegistry.registerItem(pnFish, "pnFish");
        GameRegistry.registerItem(pnFish2, "pnFish2");
        GameRegistry.registerItem(psmFish, "psmFish");
        GameRegistry.registerItem(pcFish, "pcFish");
        GameRegistry.registerItem(psFish2, "psFish2");
        GameRegistry.registerItem(phFish, "phFish");
        GameRegistry.registerItem(pmFish, "pmFish");
        GameRegistry.registerItem(pmvFish, "pmvFish");
        GameRegistry.registerItem(poFish, "poFish");
        GameRegistry.registerItem(poFish2, "poFish2");
        GameRegistry.registerItem(asFish4, "asFish4");
        GameRegistry.registerItem(acFish3, "acFish3");
        GameRegistry.registerItem(ccFish, "ccFish");
        GameRegistry.registerItem(eaFish, "eaFish");
        GameRegistry.registerItem(elFish, "elFish");
        GameRegistry.registerItem(emFish, "emFish");
        GameRegistry.registerItem(ipFish, "ipFish");
        GameRegistry.registerItem(lgFish, "lgFish");
        GameRegistry.registerItem(mdFish2, "md2Fish2");
        GameRegistry.registerItem(maFish, "maFish");
        GameRegistry.registerItem(msFish, "msFish");
        GameRegistry.registerItem(paFish4, "paFish4");
        GameRegistry.registerItem(stFish, "stFish");
        GameRegistry.registerItem(scFish, "scFish");
        GameRegistry.registerItem(aFish, "aFish");
        GameRegistry.registerItem(arFish4, "arFish4");
        GameRegistry.registerItem(caFish, "caFish");
        GameRegistry.registerItem(emFish2, "emFish2");
        GameRegistry.registerItem(enFish, "enFish");
        GameRegistry.registerItem(laFish, "laFish");
        GameRegistry.registerItem(lmFish, "lmFish");
        GameRegistry.registerItem(msFish2, "msFish2");
        GameRegistry.registerItem(mcFish3, "mcFish3");
        GameRegistry.registerItem(pfFish, "pfFish");
        GameRegistry.registerItem(pnFish4, "pnFish4");
        GameRegistry.registerItem(poFish3, "poFish3");
        GameRegistry.registerItem(sfFish2, "sfFish2");
        GameRegistry.registerItem(svFish, "svFish");
        GameRegistry.registerItem(cbFish, "cbFish");
        GameRegistry.registerItem(clFish, "clFish");
        GameRegistry.registerItem(clFish2, "clFish2");
        GameRegistry.registerItem(ccFish2, "ccFish2");
        GameRegistry.registerItem(gcFish, "gcFish");
        GameRegistry.registerItem(ioFish, "ioFish");
        GameRegistry.registerItem(ioFish2, "ioFish2");
        GameRegistry.registerItem(nbFish, "nbFish");
        GameRegistry.registerItem(sFish, "sFish");

        GameRegistry.registerItem(whiteRod, "whiteRod");
        GameRegistry.registerItem(greyRod, "greyRod");
        GameRegistry.registerItem(lightBlueRod, "lightBlueRod");
        GameRegistry.registerItem(whiteToolRod, "whiteToolRod");
        GameRegistry.registerItem(greyToolRod, "greyToolRod");
        GameRegistry.registerItem(lightBlueToolRod, "lightBlueToolRod");
        GameRegistry.registerItem(whiteReel, "whiteReel");
        GameRegistry.registerItem(greyReel, "greyReel");
        GameRegistry.registerItem(lightBlueReel, "lightBlueReel");

        GameRegistry.registerItem(copperIngot, "copperIngot");
        GameRegistry.registerItem(tinIngot, "tinIngot");
        GameRegistry.registerItem(silverIngot, "silverIngot");
        GameRegistry.registerItem(tungstenIngot, "tungstenIngot");
        GameRegistry.registerItem(arsenicIngot, "arsenicIngot");
        GameRegistry.registerItem(copperNugget, "copperNugget");
        GameRegistry.registerItem(tinNugget, "tinNugget");
        GameRegistry.registerItem(silverNugget, "silverNugget");
        GameRegistry.registerItem(tungstenNugget, "tungstenNugget");
        GameRegistry.registerItem(arsenicNugget, "arsenicNugget");

        GameRegistry.registerItem(cavierBowl, "cavierBowl");

        GameRegistry.registerItem(fishingLine, "fishingLine");
    }

}
