package com.miningmark48.bam.init;

import com.miningmark48.bam.creativetab.CreativeTabBAM;
import com.miningmark48.bam.item.*;
import com.miningmark48.bam.reference.Reference;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;

public class ModItems {

    //Fish
    public static final Item aaFish = new ItemFish().setUnlocalizedName("aaFish").setTextureName(Reference.MOD_ID + ":aaFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aaFish2 = new ItemFish().setUnlocalizedName("aaFish2").setTextureName(Reference.MOD_ID + ":aaFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aaFish3 = new ItemFish().setUnlocalizedName("aaFish3").setTextureName(Reference.MOD_ID + ":aaFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item abFish = new ItemFish().setUnlocalizedName("abFish").setTextureName(Reference.MOD_ID + ":abFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item acFish = new ItemFish().setUnlocalizedName("acFish").setTextureName(Reference.MOD_ID + ":acFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item acFish2 = new ItemFish().setUnlocalizedName("acFish2").setTextureName(Reference.MOD_ID + ":acFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item afFish = new ItemFish().setUnlocalizedName("afFish").setTextureName(Reference.MOD_ID + ":afFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ahFish = new ItemFish().setUnlocalizedName("ahFish").setTextureName(Reference.MOD_ID + ":ahFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ajFish = new ItemFish().setUnlocalizedName("ajFish").setTextureName(Reference.MOD_ID + ":ajFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ajFish2 = new ItemFish().setUnlocalizedName("ajFish2").setTextureName(Reference.MOD_ID + ":ajFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item alFish = new ItemFish().setUnlocalizedName("alFish").setTextureName(Reference.MOD_ID + ":alFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aoFish = new ItemFish().setUnlocalizedName("aoFish").setTextureName(Reference.MOD_ID + ":aoFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item anFish = new ItemFish().setUnlocalizedName("anFish").setTextureName(Reference.MOD_ID + ":anFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arFish = new ItemFish().setUnlocalizedName("arFish").setTextureName(Reference.MOD_ID + ":arFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arFish2 = new ItemFish().setUnlocalizedName("arFish2").setTextureName(Reference.MOD_ID + ":arFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arFish3 = new ItemFish().setUnlocalizedName("arFish3").setTextureName(Reference.MOD_ID + ":arFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item asFish = new ItemFish().setUnlocalizedName("asFish").setTextureName(Reference.MOD_ID + ":asFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item asFish2 = new ItemFish().setUnlocalizedName("asFish2").setTextureName(Reference.MOD_ID + ":asFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item asFish3 = new ItemFish().setUnlocalizedName("asFish3").setTextureName(Reference.MOD_ID + ":asFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish = new ItemFish().setUnlocalizedName("aspFish").setTextureName(Reference.MOD_ID + ":aspFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish2 = new ItemFish().setUnlocalizedName("aspFish2").setTextureName(Reference.MOD_ID + ":aspFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish3 = new ItemFish().setUnlocalizedName("aspFish3").setTextureName(Reference.MOD_ID + ":aspFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish4 = new ItemFish().setUnlocalizedName("aspFish4").setTextureName(Reference.MOD_ID + ":aspFish4").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish5 = new ItemFish().setUnlocalizedName("aspFish5").setTextureName(Reference.MOD_ID + ":aspFish5").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aspFish6 = new ItemFish().setUnlocalizedName("aspFish6").setTextureName(Reference.MOD_ID + ":aspFish6").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item atFish = new ItemFish().setUnlocalizedName("atFish").setTextureName(Reference.MOD_ID + ":atFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item bcFish = new ItemFish().setUnlocalizedName("bcFish").setTextureName(Reference.MOD_ID + ":bcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item bfFish = new ItemFish().setUnlocalizedName("bfFish").setTextureName(Reference.MOD_ID + ":bfFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item blFish = new ItemFish().setUnlocalizedName("blFish").setTextureName(Reference.MOD_ID + ":blFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item cfFish = new ItemFish().setUnlocalizedName("cfFish").setTextureName(Reference.MOD_ID + ":cfFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item bmFish = new ItemFish().setUnlocalizedName("bmFish").setTextureName(Reference.MOD_ID + ":bmFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item gtFish = new ItemFish().setUnlocalizedName("gtFish").setTextureName(Reference.MOD_ID + ":gtFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hcFish = new ItemFish().setUnlocalizedName("hcFish").setTextureName(Reference.MOD_ID + ":hcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item heFish = new ItemFish().setUnlocalizedName("heFish").setTextureName(Reference.MOD_ID + ":heFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hhFish = new ItemFish().setUnlocalizedName("hhFish").setTextureName(Reference.MOD_ID + ":hhFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hhFish2 = new ItemFish().setUnlocalizedName("hhFish2").setTextureName(Reference.MOD_ID + ":hhFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hpFish = new ItemFish().setUnlocalizedName("hpFish").setTextureName(Reference.MOD_ID + ":hpFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hrFish = new ItemFish().setUnlocalizedName("hrFish").setTextureName(Reference.MOD_ID + ":hrFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item isFish = new ItemFish().setUnlocalizedName("isFish").setTextureName(Reference.MOD_ID + ":isFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hsFish = new ItemFish().setUnlocalizedName("hsFish").setTextureName(Reference.MOD_ID + ":hsFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hspFish = new ItemFish().setUnlocalizedName("hspFish").setTextureName(Reference.MOD_ID + ":hspFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item hzFish = new ItemFish().setUnlocalizedName("hzFish").setTextureName(Reference.MOD_ID + ":hzFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item lcFish = new ItemFish().setUnlocalizedName("lcFish").setTextureName(Reference.MOD_ID + ":lcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ltFish = new ItemFish().setUnlocalizedName("ltFish").setTextureName(Reference.MOD_ID + ":ltFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mcFish = new ItemFish().setUnlocalizedName("mcFish").setTextureName(Reference.MOD_ID + ":mcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mcFish2 = new ItemFish().setUnlocalizedName("mcFish2").setTextureName(Reference.MOD_ID + ":mcFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mdFish = new ItemFish().setUnlocalizedName("mdFish").setTextureName(Reference.MOD_ID + ":mdFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item meFish = new ItemFish().setUnlocalizedName("meFish").setTextureName(Reference.MOD_ID + ":meFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mlFish = new ItemFish().setUnlocalizedName("mlFish").setTextureName(Reference.MOD_ID + ":mlFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item nsFish = new ItemFish().setUnlocalizedName("nsFish").setTextureName(Reference.MOD_ID + ":nsFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pwFish = new ItemFish().setUnlocalizedName("pwFish").setTextureName(Reference.MOD_ID + ":pwFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item sfFish = new ItemFish().setUnlocalizedName("sfFish").setTextureName(Reference.MOD_ID + ":sfFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item paFish = new ItemFish().setUnlocalizedName("paFish").setTextureName(Reference.MOD_ID + ":paFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item paFish2 = new ItemFish().setUnlocalizedName("paFish2").setTextureName(Reference.MOD_ID + ":paFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pdFish = new ItemFish().setUnlocalizedName("pdFish").setTextureName(Reference.MOD_ID + ":pdFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item psFish = new ItemFish().setUnlocalizedName("psFish").setTextureName(Reference.MOD_ID + ":psFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item paFish3 = new ItemFish().setUnlocalizedName("paFish3").setTextureName(Reference.MOD_ID + ":paFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pnFish3 = new ItemFish().setUnlocalizedName("pnFish3").setTextureName(Reference.MOD_ID + ":pnFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ptFish = new ItemFish().setUnlocalizedName("ptFish").setTextureName(Reference.MOD_ID + ":ptFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item smFish = new ItemFish().setUnlocalizedName("smFish").setTextureName(Reference.MOD_ID + ":smFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item vmFish = new ItemFish().setUnlocalizedName("vmFish").setTextureName(Reference.MOD_ID + ":vmFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item xhFish = new ItemFish().setUnlocalizedName("xhFish").setTextureName(Reference.MOD_ID + ":xhFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item xhFish2 = new ItemFish().setUnlocalizedName("xhFish2").setTextureName(Reference.MOD_ID + ":xhFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item nlFish = new ItemFish().setUnlocalizedName("nlFish").setTextureName(Reference.MOD_ID + ":nlFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ogFish = new ItemFish().setUnlocalizedName("ogFish").setTextureName(Reference.MOD_ID + ":ogFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item okFish = new ItemFish().setUnlocalizedName("okFish").setTextureName(Reference.MOD_ID + ":okFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item okFish2 = new ItemFish().setUnlocalizedName("okFish2").setTextureName(Reference.MOD_ID + ":okFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item omFish = new ItemFish().setUnlocalizedName("omFish").setTextureName(Reference.MOD_ID + ":omFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item omFish2 = new ItemFish().setUnlocalizedName("omFish2").setTextureName(Reference.MOD_ID + ":omFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item otFish = new ItemFish().setUnlocalizedName("otFish").setTextureName(Reference.MOD_ID + ":otFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pnFish = new ItemFish().setUnlocalizedName("pnFish").setTextureName(Reference.MOD_ID + ":pnFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pnFish2 = new ItemFish().setUnlocalizedName("pnFish2").setTextureName(Reference.MOD_ID + ":pnFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item psmFish = new ItemFish().setUnlocalizedName("psmFish").setTextureName(Reference.MOD_ID + ":psmFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pcFish = new ItemFish().setUnlocalizedName("pcFish").setTextureName(Reference.MOD_ID + ":pcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item psFish2 = new ItemFish().setUnlocalizedName("psFish2").setTextureName(Reference.MOD_ID + ":psFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item phFish = new ItemFish().setUnlocalizedName("phFish").setTextureName(Reference.MOD_ID + ":phFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pmFish = new ItemFish().setUnlocalizedName("pmFish").setTextureName(Reference.MOD_ID + ":pmFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pmvFish = new ItemFish().setUnlocalizedName("pmvFish").setTextureName(Reference.MOD_ID + ":pmvFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item poFish = new ItemFish().setUnlocalizedName("poFish").setTextureName(Reference.MOD_ID + ":poFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item poFish2 = new ItemFish().setUnlocalizedName("poFish2").setTextureName(Reference.MOD_ID + ":poFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item asFish4 = new ItemFish().setUnlocalizedName("asFish4").setTextureName(Reference.MOD_ID + ":asFish4").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item acFish3 = new ItemFish().setUnlocalizedName("acFish3").setTextureName(Reference.MOD_ID + ":acFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ccFish = new ItemFish().setUnlocalizedName("ccFish").setTextureName(Reference.MOD_ID + ":ccFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item eaFish = new ItemFish().setUnlocalizedName("eaFish").setTextureName(Reference.MOD_ID + ":eaFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item elFish = new ItemFish().setUnlocalizedName("elFish").setTextureName(Reference.MOD_ID + ":elFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item emFish = new ItemFish().setUnlocalizedName("emFish").setTextureName(Reference.MOD_ID + ":emFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ipFish = new ItemFish().setUnlocalizedName("ipFish").setTextureName(Reference.MOD_ID + ":ipFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item lgFish = new ItemFish().setUnlocalizedName("lgFish").setTextureName(Reference.MOD_ID + ":lgFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mdFish2 = new ItemFish().setUnlocalizedName("mdFish2").setTextureName(Reference.MOD_ID + ":mdFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item maFish = new ItemFish().setUnlocalizedName("maFish").setTextureName(Reference.MOD_ID + ":maFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item msFish = new ItemFish().setUnlocalizedName("msFish").setTextureName(Reference.MOD_ID + ":msFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item paFish4 = new ItemFish().setUnlocalizedName("paFish4").setTextureName(Reference.MOD_ID + ":paFish4").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item stFish = new ItemFish().setUnlocalizedName("stFish").setTextureName(Reference.MOD_ID + ":stFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item scFish = new ItemFish().setUnlocalizedName("scFish").setTextureName(Reference.MOD_ID + ":scFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item aFish = new ItemFish().setUnlocalizedName("aFish").setTextureName(Reference.MOD_ID + ":aFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item arFish4 = new ItemFish().setUnlocalizedName("arFish4").setTextureName(Reference.MOD_ID + ":arFish4").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item caFish = new ItemFish().setUnlocalizedName("caFish").setTextureName(Reference.MOD_ID + ":caFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item emFish2 = new ItemFish().setUnlocalizedName("emFish2").setTextureName(Reference.MOD_ID + ":emFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item enFish = new ItemFish().setUnlocalizedName("enFish").setTextureName(Reference.MOD_ID + ":enFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item laFish = new ItemFish().setUnlocalizedName("laFish").setTextureName(Reference.MOD_ID + ":laFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item lmFish = new ItemFish().setUnlocalizedName("lmFish").setTextureName(Reference.MOD_ID + ":lmFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item msFish2 = new ItemFish().setUnlocalizedName("msFish2").setTextureName(Reference.MOD_ID + ":msFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item mcFish3 = new ItemFish().setUnlocalizedName("mcFish3").setTextureName(Reference.MOD_ID + ":mcFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pfFish = new ItemFish().setUnlocalizedName("pfFish").setTextureName(Reference.MOD_ID + ":pfFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item pnFish4 = new ItemFish().setUnlocalizedName("pnFish4").setTextureName(Reference.MOD_ID + ":pnFish4").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item poFish3 = new ItemFish().setUnlocalizedName("poFish3").setTextureName(Reference.MOD_ID + ":poFish3").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item sfFish2 = new ItemFish().setUnlocalizedName("sfFish2").setTextureName(Reference.MOD_ID + ":sfFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item svFish = new ItemFish().setUnlocalizedName("svFish").setTextureName(Reference.MOD_ID + ":svFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item cbFish = new ItemFish().setUnlocalizedName("cbFish").setTextureName(Reference.MOD_ID + ":cbFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item clFish = new ItemFish().setUnlocalizedName("clFish").setTextureName(Reference.MOD_ID + ":clFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item clFish2 = new ItemFish().setUnlocalizedName("clFish2").setTextureName(Reference.MOD_ID + ":clFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ccFish2 = new ItemFish().setUnlocalizedName("ccFish2").setTextureName(Reference.MOD_ID + ":ccFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item gcFish = new ItemFish().setUnlocalizedName("gcFish").setTextureName(Reference.MOD_ID + ":gcFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ioFish = new ItemFish().setUnlocalizedName("ioFish").setTextureName(Reference.MOD_ID + ":ioFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item ioFish2 = new ItemFish().setUnlocalizedName("ioFish2").setTextureName(Reference.MOD_ID + ":ioFish2").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item nbFish = new ItemFish().setUnlocalizedName("nbFish").setTextureName(Reference.MOD_ID + ":nbFish").setCreativeTab(CreativeTabBAM.BAM_Tab);
    public static final Item sFish = new ItemFish().setUnlocalizedName("sFish").setTextureName(Reference.MOD_ID + ":sFish").setCreativeTab(CreativeTabBAM.BAM_Tab);

    //Rods
    public static final Item whiteRod = new ItemWhiteRod().setUnlocalizedName("whiteRod").setTextureName(Reference.MOD_ID + ":whiteRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);
    public static final Item greyRod = new ItemGreyRod().setUnlocalizedName("greyRod").setTextureName(Reference.MOD_ID + ":greyRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);
    public static final Item lightBlueRod = new ItemLightBlueRod().setUnlocalizedName("lightBlueRod").setTextureName(Reference.MOD_ID + ":lightBlueRod").setCreativeTab(CreativeTabBAM.BAM_Tab).setMaxDamage(64).setMaxStackSize(1);


    public static void init() {
        GameRegistry.registerItem(aaFish, "aaFish");
        GameRegistry.registerItem(aaFish2, "aaFish2");
        GameRegistry.registerItem(aaFish3, "aaFish3");
        GameRegistry.registerItem(abFish, "abFish");
        GameRegistry.registerItem(acFish, "acFish");
        GameRegistry.registerItem(acFish2, "acFish2");
        GameRegistry.registerItem(afFish, "afFish");
        GameRegistry.registerItem(ahFish, "ahFish");
        GameRegistry.registerItem(ajFish, "ajFish");
        GameRegistry.registerItem(ajFish2, "ajFish2");
        GameRegistry.registerItem(alFish, "alFish");
        GameRegistry.registerItem(aoFish, "aoFish");
        GameRegistry.registerItem(anFish, "anFish");
        GameRegistry.registerItem(arFish, "arFish");
        GameRegistry.registerItem(arFish2, "arFish2");
        GameRegistry.registerItem(arFish3, "arFish3");
        GameRegistry.registerItem(asFish, "asFish");
        GameRegistry.registerItem(asFish2, "asFish2");
        GameRegistry.registerItem(asFish3, "asFish3");
        GameRegistry.registerItem(aspFish, "aspFish");
        GameRegistry.registerItem(aspFish2, "aspFish2");
        GameRegistry.registerItem(aspFish3, "aspFish3");
        GameRegistry.registerItem(aspFish4, "aspFish4");
        GameRegistry.registerItem(aspFish5, "aspFish5");
        GameRegistry.registerItem(aspFish6, "aspFish6");
        GameRegistry.registerItem(atFish, "atFish");
        GameRegistry.registerItem(bcFish, "bcFish");
        GameRegistry.registerItem(bfFish, "bfFish");
        GameRegistry.registerItem(blFish, "blFish");
        GameRegistry.registerItem(bmFish, "bmFish");
        GameRegistry.registerItem(cfFish, "cfFish");
        GameRegistry.registerItem(gtFish, "gtFish");
        GameRegistry.registerItem(hcFish, "hcFish");
        GameRegistry.registerItem(heFish, "heFish");
        GameRegistry.registerItem(hhFish, "hhFish");
        GameRegistry.registerItem(hhFish2, "hhFish2");
        GameRegistry.registerItem(hpFish, "hpFish");
        GameRegistry.registerItem(hrFish, "hrFish");
        GameRegistry.registerItem(hsFish, "hsFish");
        GameRegistry.registerItem(hspFish, "hspFish");
        GameRegistry.registerItem(hzFish, "hzFish");
        GameRegistry.registerItem(isFish, "isFish");
        GameRegistry.registerItem(lcFish, "lcFish");
        GameRegistry.registerItem(ltFish, "ltFish");
        GameRegistry.registerItem(mcFish, "mcFish");
        GameRegistry.registerItem(mcFish2, "mcFish2");
        GameRegistry.registerItem(mdFish, "mdFish");
        GameRegistry.registerItem(meFish, "meFish");
        GameRegistry.registerItem(mlFish, "mlFish");
        GameRegistry.registerItem(nsFish, "nsFish");
        GameRegistry.registerItem(pwFish, "pwFish");
        GameRegistry.registerItem(sfFish, "sfFish");
        GameRegistry.registerItem(paFish, "paFish");
        GameRegistry.registerItem(paFish2, "paFish2");
        GameRegistry.registerItem(pdFish, "pdFish");
        GameRegistry.registerItem(psFish, "psFish");
        GameRegistry.registerItem(paFish3, "paFish3");
        GameRegistry.registerItem(pnFish3, "pnFish3");
        GameRegistry.registerItem(ptFish, "ptFish");
        GameRegistry.registerItem(smFish, "smFish");
        GameRegistry.registerItem(vmFish, "vmFish");
        GameRegistry.registerItem(xhFish, "xhFish");
        GameRegistry.registerItem(xhFish2, "xhFish2");
        GameRegistry.registerItem(nlFish, "nlFish");
        GameRegistry.registerItem(ogFish, "ogFish");
        GameRegistry.registerItem(okFish, "okFish");
        GameRegistry.registerItem(okFish2, "okFish2");
        GameRegistry.registerItem(omFish, "omFish");
        GameRegistry.registerItem(omFish2, "omFish2");
        GameRegistry.registerItem(otFish, "otFish");
        GameRegistry.registerItem(pnFish, "pnFish");
        GameRegistry.registerItem(pnFish2, "pnFish2");
        GameRegistry.registerItem(psmFish, "psmFish");
        GameRegistry.registerItem(pcFish, "pcFish");
        GameRegistry.registerItem(psFish2, "psFish2");
        GameRegistry.registerItem(phFish, "phFish");
        GameRegistry.registerItem(pmFish, "pmFish");
        GameRegistry.registerItem(pmvFish, "pmvFish");
        GameRegistry.registerItem(poFish, "poFish");
        GameRegistry.registerItem(poFish2, "poFish2");
        GameRegistry.registerItem(asFish4, "asFish4");
        GameRegistry.registerItem(acFish3, "acFish3");
        GameRegistry.registerItem(ccFish, "ccFish");
        GameRegistry.registerItem(eaFish, "eaFish");
        GameRegistry.registerItem(elFish, "elFish");
        GameRegistry.registerItem(emFish, "emFish");
        GameRegistry.registerItem(ipFish, "ipFish");
        GameRegistry.registerItem(lgFish, "lgFish");
        GameRegistry.registerItem(mdFish2, "md2Fish2");
        GameRegistry.registerItem(maFish, "maFish");
        GameRegistry.registerItem(msFish, "msFish");
        GameRegistry.registerItem(paFish4, "paFish4");
        GameRegistry.registerItem(stFish, "stFish");
        GameRegistry.registerItem(scFish, "scFish");
        GameRegistry.registerItem(aFish, "aFish");
        GameRegistry.registerItem(arFish4, "arFish4");
        GameRegistry.registerItem(caFish, "caFish");
        GameRegistry.registerItem(emFish2, "emFish2");
        GameRegistry.registerItem(enFish, "enFish");
        GameRegistry.registerItem(laFish, "laFish");
        GameRegistry.registerItem(lmFish, "lmFish");
        GameRegistry.registerItem(msFish2, "msFish2");
        GameRegistry.registerItem(mcFish3, "mcFish3");
        GameRegistry.registerItem(pfFish, "pfFish");
        GameRegistry.registerItem(pnFish4, "pnFish4");
        GameRegistry.registerItem(poFish3, "poFish3");
        GameRegistry.registerItem(sfFish2, "sfFish2");
        GameRegistry.registerItem(svFish, "svFish");
        GameRegistry.registerItem(cbFish, "cbFish");
        GameRegistry.registerItem(clFish, "clFish");
        GameRegistry.registerItem(clFish2, "clFish2");
        GameRegistry.registerItem(ccFish2, "ccFish2");
        GameRegistry.registerItem(gcFish, "gcFish");
        GameRegistry.registerItem(ioFish, "ioFish");
        GameRegistry.registerItem(ioFish2, "ioFish2");
        GameRegistry.registerItem(nbFish, "nbFish");
        GameRegistry.registerItem(sFish, "sFish");

        GameRegistry.registerItem(whiteRod, "whiteRod");
        GameRegistry.registerItem(greyRod, "greyRod");
        GameRegistry.registerItem(lightBlueRod, "lightBlueRod");
    }

}
